### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [nextnano/FortranInputParser#1]
I suggest adding topics such as `fortran`, `input`, `file-io` in the About section at https://github.com/nextnano/FortranInputParser.

**Comment by nextnano3** [comment]
Thanks! I added it. Makes sense!
(I am not so familiar with github and how coders work with it, so I really appreciate your feedback.)
Stefan

--------------------------------------------------------
Dr. Stefan Birner, MPhys (Managing Director)
nextnano GmbH
Konrad-Zuse-Platz 8
81829 München
Germany
Tel    +49-8121-7603205
Fax    +49-8121-7603206
Mobile +49-162-9850935
Skype: stefan.birner
***@***.******@***.***>
--------------------------------------------------------
www.nextnano.com<http://www.nextnano.com/>
www.facebook.com/nextnano<http://www.facebook.com/nextnano>
www.nextnano.com/youtube<http://www.nextnano.com/youtube>

Legal information
Managing Director: Dr. Stefan Birner
Register Court: Amtsgericht München HRB 201631
Registered address: Südmährenstr. 21, 85586 Poing

From: Beliavsky ***@***.***>
Sent: Tuesday, September 20, 2022 19:32
To: nextnano/FortranInputParser ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nextnano/FortranInputParser] add topics (Issue #1)


I suggest adding topics such as fortran, input, file-io in the About section at https://github.com/nextnano/FortranInputParser.
